### PR TITLE
Automatically choose zoom level based on latlon box

### PR DESCRIPTION
**Pull request by tomkooij**
See issue #9: 

This PR fixes the determination of map coordinates (bounding box) and implements automatic determination of zoomlevel:

```python
import smopy
map = smopy.Map((52., 4., 53., 5.))
map.show_ipython()
```

Code written by @153957

### CODE REVIEW

**Comment by rossant** [comment]
Thanks @tomkooij. Unfortunately I don't have enough time to manage this project, would you be interested in getting commit rights?

**Comment by tomkooij** [comment]
@rossant. Yes, thank you. Smopy is very useful, so commit rights to include these fixes/updates would be very useful.

**Comment by rossant** [comment]
OK https://github.com/rossant/smopy/invitations

**Comment by tomkooij** [comment]
Thanks! I will clean up this PR and merge

**Pull request merged**
